### ISSUE TITLE
Validate arrays of objects using new fluent api

### ISSUE THREAD

**Issue by gliviu** [joiful-ts/joiful#86] opened 2019-10-12 21:26 UTC
I see this example in #38

```typescript
class Bar {
    @StringSchema()
    public name!: string;
}

class Foo {
    @NestedArray(Bar)
    public myArr: Array<Bar>;
}
```
Is there a equivalent of `NestedArray` in new fluent api?
I can see `@jf.array().items(type: Joi.Schema)` but I'm not sure how to get the joi schema of `Bar`.

**Comment by codeandcats** [comment] 2019-10-13 02:53
Hi @gliviu,

You can implement array properties with nested validation like so:

```typescript
import * as jf from 'joiful';

class Bar {
    @jf.string()
    public name!: string;
}

class Foo {
    @jf.array({ elementClass: Bar })
    public myArr: Array<Bar>;
}
```

**Comment by codeandcats** [comment] 2019-10-13 03:50
Closing but please let me know if this doesn't resolve your issue. 🙂

**Closed as completed by codeandcats** 2019-10-13 03:50 UTC

**Comment by gliviu** [comment] 2019-10-14 07:29
Thanks for quick response. Works as expected.

**Comment by muthuKumar2011** [comment] 2019-10-16 09:48
Ive tried with the same for nested validation which contains Array of objects, but its not working. I am working with typescript and node js

**Comment by laurence-myers** [comment] 2019-10-16 10:25
@muthuKumar2011 could you please show the code you've tried? How does it not work - no validation?

**Comment by muthuKumar2011** [comment] 2019-10-16 10:50
@string and @name4 are customized decorators
```
class Sample{
    @string()
    key1!:string;
    @name4()
    key2!: string
}
class Validation(){
    @jf.array({elementClass:Sample})
    sampleKey?: Array<Sample>;
}
```
@laurence-myers it only validates array type. It even accepts string inside an array(**sampleKey**:["sample"]) but in my case it is an object.

**Comment by codeandcats** [comment] 2019-10-17 09:45
Hi @muthuKumar2011,

I've just [added a new test case](https://github.com/joiful-ts/joiful/blob/46b29407fbf3fd022cca9b14de3d259e123fd5e3/test/unit/decorators/array.test.ts#L31) which should cover the scenario you've described.

```typescript
class Actor {
    @string().required()
    name!: string;
}

class Movie {
    @string().required()
    name!: string;

    @array({ elementClass: Actor }).required()
    actors!: Actor[];
}
```

This movie is considered valid

```typescript
{
    name: 'The Faketrix',
    actors: [
        { name: 'Laurence Fishberg' },
        { name: 'Keanu Wick' },
        { name: 'Carrie-Anne More' },
    ],
}
```

While these movies are considered invalid

```typescript
[
    {
        name: 'The Faketrix',
        actors: [
            { name: 'Laurence Fishberg' },
            {},
            { name: 'Carrie-Anne More' },
        ],
    },
    {
        name: 'The Faketrix',
        actors: [1, 2, 3],
    },
    {
        name: 'The Faketrix',
        actors: [
            'Laurence Fishberg',
            'Keanu Wick',
            'Carrie-Anne More',
        ],
    },
]
```

The test seems to behave exactly as expected so I've not been able to reproduce your results. I think the best way for us to help would be if you can create a small repository which reproduces your issue. 🙏
