### ISSUE TITLE
Requesting support for validating inherited fields

### ISSUE THREAD

**Issue by jpbaking** [joiful-ts/joiful#222] opened 2021-08-18 03:34 UTC
Given:
```typescript
export class Foo {
  @joi.string().required().min(3).regex(/[a-zA-Z][a-zA-Z0-9-_]+[a-zA-Z0-9]/)
  foo: string;
}
export class Bar extends Foo {
  @joi.string().required().min(3).regex(/[a-zA-Z][a-zA-Z0-9-_]+[a-zA-Z0-9]/)
  bar: string;
}
```
When:
```typescript
import * as jf from 'joiful';
const bar: Bar = new Bar();
// bar.foo // undefined
bar.bar = 'sample-val1d_value'
const { error } = jf.validate(bar);
```
Expect:
```typescript
// jest-ish
expect(error?.details?.length).toStrictEqual(1) // should be because of bar.foo
```
Actual:
```typescript
// jest-ish
expect(error?.details?.length).toStrictEqual(0) // bar.foo completely missed :'(
```

**Comment by laurence-myers** [comment] 2021-08-18 04:01
Hmm, weird. We have tests for validating inherited properties, so it should be supported. We'll need to investigate.

https://github.com/joiful-ts/joiful/blob/master/test/unit/inheritance.test.ts

**Comment by laurence-myers** [comment] 2021-08-18 08:05
I can't reproduce this issue. I added the test case to `inheritance.test.ts`, and it passes.

Is it possible that you have not imported `reflect-metadata` in your application's entry point, or you have imported it in multiple files? (Importing it mulitple times might create multiple metadata maps/caches)

```typescript
    it('works for issue #222', () => {
        class Foo {
            @jf.string().required().min(3).regex(/[a-zA-Z][a-zA-Z0-9-_]+[a-zA-Z0-9]/)
            foo!: string;
        }
        class Bar extends Foo {
            @jf.string().required().min(3).regex(/[a-zA-Z][a-zA-Z0-9-_]+[a-zA-Z0-9]/)
            bar!: string;
        }

        const bar: Bar = new Bar();
        // bar.foo // undefined
        bar.bar = 'sample-val1d_value';
        const { error } = validator.validate(bar);
        expect(error?.details?.length).toStrictEqual(1); // should be because of bar.foo
    });
```

![image](https://user-images.githubusercontent.com/6336048/129861662-66c68d0f-a5cb-4694-ac69-852c4b02b454.png)

**Comment by laurence-myers** [comment] 2022-04-03 02:27
Closing. If you still have this problem, please provide a minimal reproducible example.

**Closed as completed by laurence-myers** 2022-04-03 02:27 UTC
Labels: invalid
