### ISSUE TITLE
Nested objects not validating

### ISSUE THREAD

**Issue by randy-halim** [joiful-ts/joiful#226] opened 2021-09-23 17:22 UTC
I have two classes, one referencing another:
```ts
class Address {
  @(jf.string().required().label("Address Line 1").min(1))
  line1!: string;

  @(jf.string().label("Address Line 2"))
  line2?: string;

  // so on...
}
class RegisterDetails {
  // ...
  
  @(jf.object.required())
  address_shipping!: Address;
}
```
When I validate with `RegisterDetails`, all the normal validators (strings, numbers, etc.) work as expected; the nested object is not. Does anyone have any ideas on what's going on? Thanks!

**Comment by laurence-myers** [comment] 2021-09-24 00:38
You might need to explicitly call each decorator method. Does
`@(jf.object().required())` work?

**Comment by laurence-myers** [comment] 2022-04-03 02:28
Closing.

**Closed as completed by laurence-myers** 2022-04-03 02:28 UTC
Labels: invalid

**Comment by kogratte** [comment] 2023-12-13 15:57
Sorry guys, but I can reproduce the exact same issue, and the answer to the question is a big "nop, it does not work". Why is this issue closed?

**Comment by kogratte** [comment] 2023-12-13 16:05
More context.

```ts
class Item implements TItem
{
    @object().optional()
    child?: TChild;
}

class Child implements TChild {
   @string().required().min(10).max(30)
    content = "";
}
```

When invoking validation with the following code
```ts
 const result = jf.validateAsClass({ child: { content: "" } }, Item, {
        allowUnknown: true,        
    });
```

I got a valid result, despite the fact content being clearly invalid.

May it be due to the usage of interface instead of plain objects?

**Comment by laurence-myers** [comment] 2023-12-13 19:38
> May it be due to the usage of interface instead of plain objects?

Nested objects must be a class, not an interface. This is because interfaces don't exist at runtime, and can't accept decorators. Although you have added decorators to the `Child` class, there are no decorators on `TChild`, so no validation occurs.

Here's an example from the unit tests:

https://github.com/joiful-ts/joiful/blob/f0c977ba09b66bb0368b436c8fb478dda7040153/test/unit/examples.test.ts#L56-L76

**Comment by kogratte** [comment] 2023-12-13 21:28
Then I guess I have to roll back to the row joi :)

Thanks for the quick reply!

**Comment by laurence-myers** [comment] 2023-12-17 01:13
> Then I guess I have to roll back to the [raw] joi :)

I'm not sure why. joiful will work if you change this:

```typescript
    child?: TChild;
```

To this:

```typescript
    child?: Child;
```

Or, if you want to keep it as an interface, pass the class to the decorator options:

```typescript
    @object({ objectClass: Child }).optional()
    child?: TChild;
```

**Comment by kogratte** [comment] 2023-12-17 01:19
There is a reason I'm using interfaces and not implementation :)
